// That code below is generated automatically. Do not change them manually!
import _init from 'modules/_default/_init/index';
import fwBank from 'modules/_default/fwBank/index';
import fwCategory from 'modules/_default/fwCategory/index';
import fwCluster from 'modules/_default/fwCluster/index';
import fwComment from 'modules/_default/fwComment/index';
import fwEmail from 'modules/_default/fwEmail/index';
import fwHome from 'modules/_default/fwHome/index';
import fwMenu from 'modules/_default/fwMenu/index';
import fwNotification from 'modules/_default/fwNotification/index';
import fwRate from 'modules/_default/fwRate/index';
import fwRole from 'modules/_default/fwRole/index';
import fwUser from 'modules/_default/fwUser/index';
import fwCandidate from 'modules/mdDaoTao/fwCandidate/index';
import fwCar from 'modules/mdDaoTao/fwCar/index';
import fwCertificate from 'modules/mdDaoTao/fwCertificate/index';
import fwChangeLecturer from 'modules/mdDaoTao/fwChangeLecturer/index';
import fwChat from 'modules/mdDaoTao/fwChat/index';
import fwCourse from 'modules/mdDaoTao/fwCourse/index';
import fwCourseType from 'modules/mdDaoTao/fwCourseType/index';
import fwDivision from 'modules/mdDaoTao/fwDivision/index';
import fwDriveQuestion from 'modules/mdDaoTao/fwDriveQuestion/index';
import fwDriveTest from 'modules/mdDaoTao/fwDriveTest/index';
import fwLesson from 'modules/mdDaoTao/fwLesson/index';
import fwPayment from 'modules/mdDaoTao/fwPayment/index';
import fwRegisterCalendar from 'modules/mdDaoTao/fwRegisterCalendar/index';
import fwSign from 'modules/mdDaoTao/fwSign/index';
import fwStudent from 'modules/mdDaoTao/fwStudent/index';
import fwSubject from 'modules/mdDaoTao/fwSubject/index';
import fwTimeTable from 'modules/mdDaoTao/fwTimeTable/index';
import fwContact from 'modules/mdTruyenThong/fwContact/index';
import fwFeedback from 'modules/mdTruyenThong/fwFeedback/index';
import fwForum from 'modules/mdTruyenThong/fwForum/index';
import fwNews from 'modules/mdTruyenThong/fwNews/index';
import fwNotificationTemplate from 'modules/mdTruyenThong/fwNotificationTemplate/index';
import fwSubscribe from 'modules/mdTruyenThong/fwSubscribe/index';

export const modules = [_init, fwBank, fwCategory, fwCluster, fwComment, fwEmail, fwHome, fwMenu, fwNotification, fwRate, fwRole, fwUser, fwCandidate, fwCar, fwCertificate, fwChangeLecturer, fwChat, fwCourse, fwCourseType, fwDivision, fwDriveQuestion, fwDriveTest, fwLesson, fwPayment, fwRegisterCalendar, fwSign, fwStudent, fwSubject, fwTimeTable, fwContact, fwFeedback, fwForum, fwNews, fwNotificationTemplate, fwSubscribe];