// That code below is generated automatically. Do not change them manually!
import _init from 'modules/_default/_init/index';
import fwComment from 'modules/_default/fwComment/index';
import fwCourseFee from 'modules/_default/fwCourseFee/index';
import fwCoursePayment from 'modules/_default/fwCoursePayment/index';
import fwDepartment from 'modules/_default/fwDepartment/index';
import fwDiscount from 'modules/_default/fwDiscount/index';
import fwEncryption from 'modules/_default/fwEncryption/index';
import fwEnrollTarget from 'modules/_default/fwEnrollTarget/index';
import fwFeeType from 'modules/_default/fwFeeType/index';
import fwHome from 'modules/_default/fwHome/index';
import fwMenu from 'modules/_default/fwMenu/index';
import fwNotification from 'modules/_default/fwNotification/index';
import fwProfileType from 'modules/_default/fwProfileType/index';
import fwStaff from 'modules/_default/fwStaff/index';
import fwTeacher from 'modules/_default/fwTeacher/index';
import fwTeacherDiploma from 'modules/_default/fwTeacherDiploma/index';
import fwTrainingClass from 'modules/_default/fwTrainingClass/index';
import fwUser from 'modules/_default/fwUser/index';
import fwCandidate from 'modules/mdDaoTao/fwCandidate/index';
import fwCertificate from 'modules/mdDaoTao/fwCertificate/index';
import fwChangeLecturer from 'modules/mdDaoTao/fwChangeLecturer/index';
import fwCourse from 'modules/mdDaoTao/fwCourse/index';
import fwCourseType from 'modules/mdDaoTao/fwCourseType/index';
import fwDivision from 'modules/mdDaoTao/fwDivision/index';
import fwLicenseTest from 'modules/mdDaoTao/fwLicenseTest/index';
import fwProfileStudentType from 'modules/mdDaoTao/fwProfileStudentType/index';
import fwReviewClass from 'modules/mdDaoTao/fwReviewClass/index';
import fwStudyProgram from 'modules/mdDaoTao/fwStudyProgram/index';
import fwContact from 'modules/mdTruyenThong/fwContact/index';
import fwFaq from 'modules/mdTruyenThong/fwFaq/index';
import fwLaw from 'modules/mdTruyenThong/fwLaw/index';
import fwNews from 'modules/mdTruyenThong/fwNews/index';
import fwSubscribe from 'modules/mdTruyenThong/fwSubscribe/index';

export const modules = [_init, fwComment, fwCourseFee, fwCoursePayment, fwDepartment, fwDiscount, fwEncryption, fwEnrollTarget, fwFeeType, fwHome, fwMenu, fwNotification, fwProfileType, fwStaff, fwTeacher, fwTeacherDiploma, fwTrainingClass, fwUser, fwCandidate, fwCertificate, fwChangeLecturer, fwCourse, fwCourseType, fwDivision, fwLicenseTest, fwProfileStudentType, fwReviewClass, fwStudyProgram, fwContact, fwFaq, fwLaw, fwNews, fwSubscribe];